- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  vars:
    keypair: serversuit
    instance_type: t2.micro
    security_group: ServerSuitSecurityGroup
    image: ami-0015b9ef68c77328d
    region: us-east-1
  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ keypair }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: subnet-86a9b1db
         user_data: |
                    #!/bin/sh
                    yum install docker -y
                    service docker start
                    docker pull gupta220/xspring-pet
         assign_public_ip: yes
      register: ec2

    - name: Waiting for the instance to come
      local_action: wait_for
                    host={{ item.public_ip }}
                    state=started
                    port=22
      with_items: '{{ ec2.instances }}'
